<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>arsiy.Rooms</RootNamespace>
    <TargetFramework>net472</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <LangVersion>10</LangVersion>
    <OutputPath>../Assemblies</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>None</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref">
      <Version>1.6.*</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony">
      <Version>2.2.*</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
